
import { Outlet } from './types';

export const OUTLETS: Outlet[] = [
  'Kota - DMC NAMA OUTLET',
'Band Aceh - DMC Nagan Raya',
'Bandar Jaya - DMC Bandar Jaya',
'Bandar Lampung - DMC Gedung Meneng',
'Bandung - DMC Ahmad Yani Bandung',
'Bandung - DMC Bandung Ciparay',
'Bandung - DMC Bojongsoang',
'Bandung - DMC Caringin Bandung',
'Bandung - DMC Cibiru Bandung',
'Bandung - DMC Ciburuy Bandung',
'Bandung - DMC Cikutra Bandung',
'Bandung - DMC Cimareme Bandung',
'Bandung - DMC Gadobangkong',
'Bandung - DMC Kamasan',
'Bandung - DMC Majalaya',
'Bandung - DMC Pinggir Wangi',
'Cimahi - DMC Pusat Cihanjuang',
'Bandung - DMC Rencong',
'Bandung - DMC Sarijadi',
'Bandung - DMC Soreang',
'Bandung - DMC Taman Kopo Indah',
'Bandung - DMC Ujung Berung',
'Bangko - DMC Bangko Jambi',
'Banjar - DMC Banjar',
'Banjarnegara - DMC Banjarnegara',
'Bantul - DMC Bantul Yogyakarta',
'BatuSangkar - DMC Batu Sangkar',
'Bekasi - DMC Bekasi Mutiara Gading',
'Bekasi - DMC Bekasi SPBU Perwira',
'Bekasi - DMC Bekasi Villa Gading',
'Bekasi - DMC Jababeka',
'Bekasi - DMC Jatiwarna (Puri Gading)',
'Bogor - DMC Bogor Ciseeng',
'Bogor - DMC Bukit Dago',
'Bogor - DMC Cibubur Country',
'Bogor - DMC Cikaret',
'Bogor - DMC Citayam',
'Bogor - DMC Cogreg',
'Bogor - DMC Gunung Batu',
'Bogor - DMC Indra Prasta',
'Bogor - DMC Lawang Gintung',
'Bogor - DMC Metland Transyiogi Cileungsi',
'Bogor - DMC Parung Panjang',
'Bogor - DMC Ruang Iqra Ciapus',
'Bogor - DMC Semplak Bogor',
'Bogor - DMC Tajur',
'Bogor - DMC Vila Bogor Indah',
'Ciamis - DMC Ciamis',
'Ciamis - DMC Ciamis Kawali',
'Cianjur - DMC Kota Cianjur',
'Cikampek - DMC Cikampek',
'Cikampek - DMC Cikampek Parakan',
'Cikarang - DMC Cibarusah',
'Cilacap - DMC Majenang',
'Cilacap - DMC Sidareja',
'Cilegon - DMC Cilegon Jombang Masjid',
'Cilegon - DMC Merak',
'Cirebon - DMC Cirebon',
'Cirebon - DMC Cirebon Arjawinangun',
'Cirebon - DMC Cirebon Ciledug',
'Cirebon - DMC Cirebon Plered',
'Cirebon - DMC Harjamukti Cirebon',
'Cirebon - DMC Indramayu',
'Cirebon - DMC Indramayu Jatibarang',
'Cirebon - DMC Indramayu Karang Ampel',
'Cirebon - DMC Jatiwangi',
'Cirebon - DMC Palimanan',
'Cirebon - DMC Sumber Cirebon',
'Cirebon - DMC Sumber Cirebon 2',
'Depok - DMC Cilodong',
'Depok - DMC Cinere',
'Depok - DMC Maharaja Depok',
'Depok - DMC Nusantara Depok',
'Depok - DMC SPBU Sawangan',
'Depok - DMC Tole',
'Dharmasraya - DMC Padang Pulau Punjung',
'Garut - DMC Limbangan',
'Gayamprit - DMC Gayamprit',
'Indra Giri Hulu - DMC Indra Giri Hulu',
'Indra Giri Hulu - DMC Tembilahan',
'Jakarta Selatan - DMC Jagakarsa',
'Jakarta Timur - DMC Kalisari',
'Jambi - DMC Sungai Penuh',
'Kalawi - DMC Padang Kalawi',
'Karawang - DMC Karawang Cilamaya',
'Klaten - DMC Klaten Wedi DMS Wedi',
'Kuningan - DMC Jalaksana Kuningan',
'Kuningan - DMC Luragung',
'Kuningan - DMC Re Marthadinata',
'Lahat - DMC Palembang Lahat',
'Lapai - DMC Lapai Padang',
'Lebak - DMC Lebak Banten',
'Madiun - DMC Madiun',
'Magetan - DMC Yos Sudarso Magetan',
'Majalengka - DMC K. H Abdul Halim Majalengka',
'Majalengka - DMC Rajagaluh',
'Meulaboh - DMC Aceh Meulaboh',
'Muaro Bungo - DMC Muara Bungo',
'Ngawi - DMC Ngawi',
'Padang - DMC Padang Pariaman',
'Padang - DMC Padang Tabing',
'Padang - DMC Soetomo Padang',
'Painan - DMC Painan',
'Pandeglang - DMC Labuan',
'Pandeglang - DMC Pandeglang',
'Pangandaran - DMC Pangandaran',
'Pasaman Barat - DMC Pasaman Barat',
'Payakumbuh - DMC Payakumbuh',
'Ponorogo - DMC Ponorogo',
'Prabu Mulih - DMC Muara Enim',
'Pringsewu - DMC Lampung Pringsewu',
'Purbalingga - DMC Purbalingga',
'Purwakarta - DMC Kosambi Karawang',
'Purwodadi - DMC Purwodadi',
'Rokan Hulu - DMC Rokan Hulu',
'Sarolangun - DMC Sarolangun',
'Semarang - DMC Banyumanik Semarang',
'Semarang - DMC Kedungmundu',
'Serang - DMC Serang',
'Solo - DMC Solo Mr Sartono',
'Sragen - DMC Sragen',
'Subang - DMC Cigadung Subang',
'Subang - DMC Kalijati',
'Subang - DMC Pabuaran Subang',
'Subang - DMC Pamanukan Subang',
'Subang - DMC Subang Pagaden',
'Sukabumi - DMC Cicurug Sukabumi',
'Sukabumi - DMC Cipanengah',
'Sukabumi - DMC Cisaat Sukabumi',
'Sukabumi - DMC Pelabuhan Ratu',
'Sukabumi - DMC Sukabumi Cibadak',
'Sukoharjo - DMC Sukoharjo',
'Sumedang - DMC Regol Wetan Sumedang',
'Sumedang - DMC Tanjungsari',
'Sungai Rumbai - DMC Jambi Sungai Rumbai',
'Surantih Kambang - DMC Surantih',
'Tangerang - DMC Aria Putra Ciputat',
'Tangerang - DMC Tangerang Cijantra',
'Tangerang Selatan - DMC Lengkong',
'Tangerang Selatan - DMC Pamulang 2',
'Tangerang Selatan - DMC Pondok Aren',
'Tangerang Selatan - DMC Serpong Garden',
'Tasikmalaya - DMC Ciawi Tasikmalaya',
'Tasikmalaya - DMC Indihiang Tasikmalaya',
'Tasikmalaya - DMC Singaparna',
'Temanggung - DMC Temanggung',
'Wonogiri - DMC Wonogiri',
'Wonosobo - DMC Wonosobo',
'Yogyakarta - DMC Perintis'
];
